---
- hosts: rdnsslave
  user: vinod
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
       - /etc/ansible/roles/rdnsslave/inputs/inputsrdns.yml
  any_errors_fatal: true
  tasks:
  roles:

   - dependencies
   - rdnsslave
